theme: osuny
_merge: deep
params:
  menu:
    dropdown:
      linkToLevel1: true
  summary:
    position: content
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  posts:
    index:
      layout: grid
      options:
        author: true
        categories: true
        date: true
        image: false
        reading_time: false
        summary: true
        subtitle: true
    single:
      author_signature: true
