theme: osuny
_merge: deep
params:
  plausible: lucienseve.org
  menu:
    primary:
      level_2:
        title:
          active: true
  summary:
    position: content
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  posts:
    date_format: "2006"
    index:
      layout: list
      options:
        author: false
        categories: true
        date: true
        image: false
        reading_time: false
        summary: true
        subtitle: true
    single:
      author_signature: true
